Repository GSG-CF05/CryptoCoin, pull requests merged in 2022-03, with the labels that each got.

#2 1 create file structure
  CSS/normalize.css
  CSS/style.css
  index.html
  script.js
Labels: Approve

#4 Folder containing 10 single GIF icons
  assets/ArrowBopUp.svg
  assets/ArrowIcon.svg
  assets/Bitcoin.svg
  assets/Chainlink.svg
  assets/ConvertIcon.svg
  assets/DarkIcon.svg
  assets/Etherium.svg
  assets/LightIcon.svg
  assets/Litecoin.svg
  assets/TeamDevIcon.svg
  assets/copyCoinGIF.gif
Labels: awaiting-review

#12 Done from created folder for HTML files relate#11
  HTML Folder/first.html
Labels: awaiting-review

#13 create welcome page html
  CSS/style.css
  README.md
  index.html
Labels: awaiting-review

#17 create README page
  README.md
Labels: Approve, awaiting-review
